[allowlist]
  description = "Global Allowlist"

  # Ignore based on any subset of the file path
  paths = [
    # Ignore some long path
    '''testutils\/helm\/server.key$''',
    '''testutils\/helm\/client.key$''',
    '''testutils\/helm\/ca.key$''',
  ]