apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "clustertemplate.openshift.io/v1alpha1",
          "kind": "ClusterTemplate",
          "metadata": {
            "name": "clustertemplate-sample"
          },
          "spec": {}
        },
        {
          "apiVersion": "clustertemplate.openshift.io/v1alpha1",
          "kind": "ClusterTemplateInstance",
          "metadata": {
            "name": "clustertemplateinstance-sample"
          },
          "spec": {}
        },
        {
          "apiVersion": "clustertemplate.openshift.io/v1alpha1",
          "kind": "ClusterTemplateQuota",
          "metadata": {
            "name": "clustertemplatequota-sample"
          },
          "spec": {}
        }
      ]
    capabilities: Basic Install
    categories: Integration & Delivery,OpenShift Optional
    certified: "false"
    description: Easily install fully configured clusters with guard-rails.
    operators.operatorframework.io/builder: operator-sdk-v1.22.2
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: cluster-templates-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Represents a request for instance of cluster
      displayName: Cluster Template Instance
      kind: ClusterTemplateInstance
      name: clustertemplateinstances.clustertemplate.openshift.io
      version: v1alpha1
    - description: Defines which ClusterTemplates can be used in a given namespace
      displayName: Cluster Template Quota
      kind: ClusterTemplateQuota
      name: clustertemplatequotas.clustertemplate.openshift.io
      version: v1alpha1
    - description: Template of a cluster - defines resources required to start the
        installation (via Helm chart) and optionally a post install setup of the cluster
        (via Tekton pipeline)
      displayName: Cluster Template
      kind: ClusterTemplate
      name: clustertemplates.clustertemplate.openshift.io
      version: v1alpha1
  description: |
    **Self-service clusters with guardrails!**
    Cluster templates operator provides an easy way to define clusters as templates and allows creating instances of those templates even for non-privileged developer/devops engineers. Cluster templates operator also allows specifing quotas for the developer/devops engineers.

    Tekton pipelines are used for post installation cluster setup. If you want to leverage the feature, make sure to install the Tekton operator.
  displayName: Cluster Templates
  icon:
  - base64data: PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA3MjEuMTUgNzIxLjE1Ij48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2RiMzkyNzt9LmNscy0ye2ZpbGw6I2NiMzYyODt9LmNscy0ze2ZpbGw6I2ZmZjt9LmNscy00e2ZpbGw6I2UzZTNlMjt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPlByb2R1Y3RfSWNvbi1SZWRfSGF0QWR2YW5jZWRfQ2x1c3Rlcl9NYW5hZ2VtZW50X2Zvcl9LdWJlcm5ldGVzLVJHQjwvdGl0bGU+PGcgaWQ9IkxheWVyXzEiIGRhdGEtbmFtZT0iTGF5ZXIgMSI+PGNpcmNsZSBjbGFzcz0iY2xzLTEiIGN4PSIzNjAuNTciIGN5PSIzNjAuNTciIHI9IjM1OC41OCIvPjxwYXRoIGNsYXNzPSJjbHMtMiIgZD0iTTYxNC4xMywxMDcsMTA3LDYxNC4xM2MxNDAsMTQwLDM2Ny4wNywxNDAsNTA3LjExLDBTNzU0LjE2LDI0Ny4wNiw2MTQuMTMsMTA3WiIvPjxyZWN0IGNsYXNzPSJjbHMtMyIgeD0iMzMwLjg3IiB5PSIyODAuNiIgd2lkdGg9IjIwMy4xNyIgaGVpZ2h0PSIyMCIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTc4LjkgMzkwLjUyKSByb3RhdGUoLTQ0Ljk2KSIvPjxyZWN0IGNsYXNzPSJjbHMtMyIgeD0iMzA2LjYzIiB5PSIxNjcuODMiIHdpZHRoPSIyMCIgaGVpZ2h0PSIyMDQuNDciIHRyYW5zZm9ybT0idHJhbnNsYXRlKC04NS4zMyAxNjIuMjcpIHJvdGF0ZSgtMjUuNDUpIi8+PHJlY3QgY2xhc3M9ImNscy0zIiB4PSIxNjIuOTgiIHk9IjM2NC4xIiB3aWR0aD0iMTk4LjI4IiBoZWlnaHQ9IjIwIiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgtNDIuMzkgMzMuNjEpIHJvdGF0ZSgtNi43OSkiLz48cmVjdCBjbGFzcz0iY2xzLTMiIHg9IjI0NS4xIiB5PSI0NTEuNTQiIHdpZHRoPSIyMDAuNjIiIGhlaWdodD0iMjAiIHRyYW5zZm9ybT0idHJhbnNsYXRlKC0xNjMuMDEgNzMzLjI2KSByb3RhdGUoLTgxLjMxKSIvPjxyZWN0IGNsYXNzPSJjbHMtMyIgeD0iNDQzLjg1IiB5PSIzMDMuNzYiIHdpZHRoPSIyMCIgaGVpZ2h0PSIyMDcuMDQiIHRyYW5zZm9ybT0idHJhbnNsYXRlKC0xMDkuOTcgNjM5LjU4KSByb3RhdGUoLTY0LjMpIi8+PGNpcmNsZSBjbGFzcz0iY2xzLTMiIGN4PSI1MDQuMzQiIGN5PSIyMTguODMiIHI9IjQ0LjA4Ii8+PGNpcmNsZSBjbGFzcz0iY2xzLTMiIGN4PSIyNzIuNyIgY3k9IjE3Ny43NSIgcj0iNDQuMDgiLz48Y2lyY2xlIGNsYXNzPSJjbHMtMyIgY3g9IjU0Ny4xMiIgY3k9IjQ1Mi4xNyIgcj0iNDQuMDgiLz48Y2lyY2xlIGNsYXNzPSJjbHMtMyIgY3g9IjE2My42OCIgY3k9IjM4NS44MiIgcj0iNDQuMDgiLz48Y2lyY2xlIGNsYXNzPSJjbHMtMyIgY3g9IjMzMC4yNiIgY3k9IjU2MC43IiByPSI0NC4wOCIvPjxwYXRoIGNsYXNzPSJjbHMtNCIgZD0iTTQ0NC45NCwyNzkuOTIsMjc2LjE5LDQ0OC42N0ExMTkuMzIsMTE5LjMyLDAsMCwwLDQ0NC45NCwyNzkuOTJaIi8+PHBhdGggY2xhc3M9ImNscy0zIiBkPSJNMzc1LjY4LDI0NS43NmExMTkuMzMsMTE5LjMzLDAsMCwwLTk5LjQ5LDIwMi45MUw0NDQuOTQsMjc5LjkyQTExOC44OSwxMTguODksMCwwLDAsMzc1LjY4LDI0NS43NloiLz48L2c+PC9zdmc+
    mediatype: image/svg+xml
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - update
          - watch
        - apiGroups:
          - argoproj.io
          resources:
          - applications
          verbs:
          - create
          - delete
          - get
          - list
          - watch
        - apiGroups:
          - clustertemplate.openshift.io
          resources:
          - clustertemplateinstances
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - clustertemplate.openshift.io
          resources:
          - clustertemplateinstances/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - clustertemplate.openshift.io
          resources:
          - clustertemplatequotas
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - clustertemplate.openshift.io
          resources:
          - clustertemplatequotas/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - clustertemplate.openshift.io
          resources:
          - clustertemplates
          verbs:
          - create
          - get
          - list
          - update
          - watch
        - apiGroups:
          - helm.openshift.io
          resources:
          - helmchartrepositories
          verbs:
          - create
          - get
          - list
          - update
          - watch
        - apiGroups:
          - hive.openshift.io
          resources:
          - clusterclaims
          - clusterdeployments
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - hypershift.openshift.io
          resources:
          - hostedclusters
          - nodepools
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: cluster-templates-operator-controller-manager
      deployments:
      - label:
          control-plane: controller-manager
        name: cluster-templates-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.11.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: quay.io/stolostron/cluster-templates-operator:2.7.0-7b86811828a53e6e3cc5c49cd2dc5abd6b83c9e2
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                ports:
                - containerPort: 9443
                  name: webhook-server
                  protocol: TCP
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 1Gi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: cluster-templates-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: cluster-templates-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - cluster
  - templates
  - hive
  - hypershift
  - selfservice
  - openshift
  - multicluster
  - quota
  - helm
  - pipelines
  links:
  - name: Cluster Templates
    url: https://cluster-templates-operator.domain
  maintainers:
  - email: rawagner@redhat.com
    name: Rastislav Wagner
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.0.1
  webhookdefinitions:
  - admissionReviewVersions:
    - v1
    containerPort: 443
    conversionCRDs:
    - clustertemplateinstances.clustertemplate.openshift.io
    - clustertemplatequotas.clustertemplate.openshift.io
    deploymentName: cluster-templates-operator-controller-manager
    generateName: cclustertemplateinstancesclustertemplatequotas.kb.io
    sideEffects: None
    targetPort: 9443
    type: ConversionWebhook
    webhookPath: /convert
  - admissionReviewVersions:
    - v1
    containerPort: 443
    deploymentName: cluster-templates-operator-controller-manager
    failurePolicy: Fail
    generateName: vclustertemplateinstance.kb.io
    rules:
    - apiGroups:
      - clustertemplate.openshift.io
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - clustertemplateinstances
    sideEffects: None
    targetPort: 9443
    type: ValidatingAdmissionWebhook
    webhookPath: /validate-clustertemplate-openshift-io-v1alpha1-clustertemplateinstance
  - admissionReviewVersions:
    - v1
    containerPort: 443
    deploymentName: cluster-templates-operator-controller-manager
    failurePolicy: Fail
    generateName: vclustertemplatequota.kb.io
    rules:
    - apiGroups:
      - clustertemplate.openshift.io
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      resources:
      - clustertemplatequotas
    sideEffects: None
    targetPort: 9443
    type: ValidatingAdmissionWebhook
    webhookPath: /validate-clustertemplate-openshift-io-v1alpha1-clustertemplatequota
