---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - agent.open-cluster-management.io
  resources:
  - klusterletaddonconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - applicationsets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - argocds
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclusters
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclustersets/join
  verbs:
  - create
- apiGroups:
  - clustertemplate.openshift.io
  resources:
  - clustertemplateinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clustertemplate.openshift.io
  resources:
  - clustertemplateinstances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - clustertemplate.openshift.io
  resources:
  - clustertemplatequotas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clustertemplate.openshift.io
  resources:
  - clustertemplatequotas/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - clustertemplate.openshift.io
  resources:
  - clustertemplates
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - clustertemplate.openshift.io
  resources:
  - clustertemplates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - clustertemplate.openshift.io
  resources:
  - clustertemplatesetup
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - clustertemplate.openshift.io
  resources:
  - clustertemplatesetup/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - clustertemplate.openshift.io
  resources:
  - config
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - console.openshift.io
  resources:
  - consoleplugins
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - console.openshift.io
  resources:
  - consolequickstarts
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - hive.openshift.io
  resources:
  - clusterclaims
  - clusterdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hypershift.openshift.io
  resources:
  - hostedclusters
  - nodepools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operators.coreos.com
  resources:
  - subscriptions
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - register.open-cluster-management.io
  resources:
  - managedclusters/accept
  verbs:
  - update
