---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - clustertemplate.openshift.io
  resources:
  - clustertemplateinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clustertemplate.openshift.io
  resources:
  - clustertemplateinstances/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - clustertemplate.openshift.io
  resources:
  - clustertemplatequotas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clustertemplate.openshift.io
  resources:
  - clustertemplatequotas/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - clustertemplate.openshift.io
  resources:
  - clustertemplates
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - helm.openshift.io
  resources:
  - helmchartrepositories
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - hive.openshift.io
  resources:
  - clusterclaims
  - clusterdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hypershift.openshift.io
  resources:
  - hostedclusters
  - nodepools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
