apiVersion: hypershift.openshift.io/v1alpha1
kind: HostedCluster
metadata:
  name: {{ .Release.Namespace }}-{{ .Release.Name }}
spec:
  release:
    image: quay.io/openshift-release-dev/ocp-release:{{ .Values.ocpVersion }}-{{ .Values.ocpArch }}
  pullSecret:
    name: pullsecret-cluster
  sshKey:
    name: sshkey-cluster
  networking:
    podCIDR: 10.132.0.0/14
    serviceCIDR: 172.31.0.0/16
    machineCIDR: 192.168.122.0/24
    networkType: OVNKubernetes
  platform:
    type: None
  infraID: {{ .Release.Namespace }}-{{ .Release.Name }}
  dns:
    baseDomain: {{ .Values.baseDnsDomain }}
  services:
  - service: APIServer
    servicePublishingStrategy:
      type: {{ .Values.APIPublishingStrategy }}
  - service: OAuthServer
    servicePublishingStrategy:
      type: Route
  - service: OIDC
    servicePublishingStrategy:
      type: Route
  - service: Konnectivity
    servicePublishingStrategy:
      type: Route
  - service: Ignition
    servicePublishingStrategy:
      type: Route