apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    categories: Integration & Delivery,OpenShift Optional
    certified: "false"
    containerImage: quay.io/stolostron/cluster-templates-operator:2.7.0-01b066819809ae9446713ec7f403d4357f70954c
    createdAt: "2022-11-25T12:00:00+00:00"
    description: Easily install fully configured clusters with guard-rails.
    repository: https://github.com/stolostron/cluster-templates-operator
  name: cluster-aas-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Represents instance of a cluster
      displayName: Cluster template instance
      kind: ClusterTemplateInstance
      name: clustertemplateinstances.clustertemplate.openshift.io
      resources:
      - kind: Pod
        name: ""
        version: v1
      statusDescriptors:
      - description: A reference for secret which contains username and password under
          keys "username" and "password"
        displayName: Admin Password
        path: adminPassword
      - description: API server URL of the new cluster
        displayName: APIserver URL
        path: apiServerURL
      - description: Status of each cluster setup
        displayName: Cluster Setup
        path: clusterSetup
      - description: Resource conditions
        displayName: Conditions
        path: conditions
      - description: A reference for secret which contains kubeconfig under key "kubeconfig"
        displayName: Kubeconfig
        path: kubeconfig
      - description: Additional message for Phase
        displayName: Message
        path: message
      - description: Represents instance installaton & setup phase
        displayName: Phase
        path: phase
      version: v1alpha1
    - description: Defines which ClusterTemplates can be used in a given namespace
      displayName: Cluster template quota
      kind: ClusterTemplateQuota
      name: clustertemplatequotas.clustertemplate.openshift.io
      resources:
      - kind: Pod
        name: ""
        version: v1
      statusDescriptors:
      - description: How much budget is currenly spent
        displayName: Budget Spent
        path: budgetSpent
      - description: Which instances are in use
        displayName: Template Instances
        path: templateInstances
      version: v1alpha1
    - description: Template of a cluster - both installation and post-install setup
        are defined as ArgoCD application spec. Any application source is supported
        - typically a Helm chart
      displayName: Cluster template
      kind: ClusterTemplate
      name: clustertemplates.clustertemplate.openshift.io
      resources:
      - kind: Pod
        name: ""
        version: v1
      version: v1alpha1
  description: |
    **Self-service clusters with guardrails!**
    Cluster as a service operator provides an easy way to define clusters as templates and allows creating instances of those templates even for non-privileged developer/devops engineers. Cluster templates operator also allows specifing quotas for the developer/devops engineers.

    ### Documentation
    Documentation can be found on our [website](https://github.com/stolostron/cluster-templates-operator).

    ### Getting help
    To report any issues or ask questions, create an issue on our [Github repo](https://github.com/stolostron/cluster-templates-operator/issues)
  displayName: Cluster as a service operator
  icon:
  - base64data: PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTguNTEgMjU4LjUxIj48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2QxZDFkMTt9LmNscy0ye2ZpbGw6IzhkOGQ4Zjt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPkFzc2V0IDQ8L3RpdGxlPjxnIGlkPSJMYXllcl8yIiBkYXRhLW5hbWU9IkxheWVyIDIiPjxnIGlkPSJMYXllcl8xLTIiIGRhdGEtbmFtZT0iTGF5ZXIgMSI+PHBhdGggY2xhc3M9ImNscy0xIiBkPSJNMTI5LjI1LDIwQTEwOS4xLDEwOS4xLDAsMCwxLDIwNi40LDIwNi40LDEwOS4xLDEwOS4xLDAsMSwxLDUyLjExLDUyLjExLDEwOC40NSwxMDguNDUsMCwwLDEsMTI5LjI1LDIwbTAtMjBoMEM1OC4xNiwwLDAsNTguMTYsMCwxMjkuMjVIMGMwLDcxLjA5LDU4LjE2LDEyOS4yNiwxMjkuMjUsMTI5LjI2aDBjNzEuMDksMCwxMjkuMjYtNTguMTcsMTI5LjI2LTEyOS4yNmgwQzI1OC41MSw1OC4xNiwyMDAuMzQsMCwxMjkuMjUsMFoiLz48cGF0aCBjbGFzcz0iY2xzLTIiIGQ9Ik0xNzcuNTQsMTAzLjQxSDE0MS42NkwxNTQuOSw2NS43NmMxLjI1LTQuNC0yLjMzLTguNzYtNy4yMS04Ljc2SDEwMi45M2E3LjMyLDcuMzIsMCwwLDAtNy40LDZsLTEwLDY5LjYxYy0uNTksNC4xNywyLjg5LDcuODksNy40LDcuODloMzYuOUwxMTUuNTUsMTk3Yy0xLjEyLDQuNDEsMi40OCw4LjU1LDcuMjQsOC41NWE3LjU4LDcuNTgsMCwwLDAsNi40Ny0zLjQ4TDE4NCwxMTMuODVDMTg2Ljg2LDEwOS4yNCwxODMuMjksMTAzLjQxLDE3Ny41NCwxMDMuNDFaIi8+PC9nPjwvZz48L3N2Zz4=
    mediatype: image/svg+xml
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - cluster
  - templates
  - hive
  - hypershift
  - selfservice
  - openshift
  - multicluster
  - quota
  - helm
  - argocd
  links:
  - name: Cluster as a service operator
    url: https://github.com/stolostron/cluster-templates-operator
  maintainers:
  - email: rawagner@redhat.com
    name: Rastislav Wagner
  maturity: alpha
  minKubeVersion: 1.24.0
  provider:
    name: Stolostron
  version: 0.0.0
