name: lint

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
      - edited
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Go environment
      uses: actions/setup-go@v3.3.1
      with:
        go-version: '>=1.18.0'

    - name: install golines
      run: go install github.com/segmentio/golines@latest

    - name: run golines
      run: ./scripts/golines.sh
      shell: bash
